### ISSUE TITLE
Reg: Document

### ISSUE THREAD

**Issue by mailtoamirjohn** [kunder-lab/cordova-plugin-kunder-accountmanager#7]
Hai,

It will be more helpful if we have an document of this plugin.

Given webpage not working. [https://kunder.cl/](https://kunder.cl/)

Thanks in advance.

**Comment by arturokunder** [comment]
Hi @mailtoamirjohn 
The docs are already included in the repo [README](https://github.com/kunder-lab/cordova-plugin-kunder-accountmanager/blob/master/README.md)
The site above is the company's webpage.
